language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9"
    - "3.10"
    - "3.11"
    - "3.12"
install:
    - git submodule init
    - git submodule update
    - git submodule foreach git pull origin master
    - pip install -U setuptools coveralls
    - python bootstrap.py
    - ./bin/buildout
before_script:
    - ./bin/flake8 stop_words
script:
    - ./bin/cover
notifications:
    irc:
        - "irc.freenode.org#python-stop-words"
after_success:
    coveralls
