language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
install:
    - git submodule init
    - git submodule update
    - pip install -U setuptools
    - python bootstrap.py
    - ./bin/buildout
before_script:
    - ./bin/flake8 stop_words
script:
    - ./bin/cover
notifications:
    irc:
        - "irc.freenode.org#python-stop-words"
